{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "activeUsers_currUsers{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "averagePizzaLatency_pizzaLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "averageEndpointLatency_endpointLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizzasMade_pizzaSuccesses{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pizzasFailed_pizzaFailures{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pizzaRevenue_revenue{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(authSuccesses_successes{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(authFailures_failures{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memoryUsage_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(totalRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(getRequests_amount{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(postRequests_amount{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(putRequests_amount{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(deleteRequests_amount{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}